name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install Dependencies
        run: npm install
      - name: Build and Package
        run: npm run pack
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
